backend:
  name: git-gateway
  branch: master

locale: 'it'
media_folder: static/img
public_folder: /img

collections:
  - name: "partners"
    label: "Partners"
    folder: "content/partners"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Logo", name: "logo", widget: "string" }
  
  - name: 'pages'
    label: 'Pagine'
    editor:
      preview: false
    files:
      - label: 'Chi Siamo'
        name: 'chiSiamo'
        file: 'content/pages/chi-siamo.md'
        fields:
          - { label: 'Titolo', name: 'title', widget: 'string', default: 'Chi Siamo' }
          - { label: 'Layout', name: 'layout', widget: 'string', default: 'Chi Siamo' }
          - { label: 'Contenuto', name: 'body', widget: 'markdown' }