backend:
  name: git-gateway
  branch: master

locale: "it"
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pagine"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "content/pages/home.md"
        fields:
          - {
              label: "Titolo",
              name: "title",
              widget: "string",
              default: "Chi Siamo",
            }
          - { label: "Introduzione", name: "introduction", widget: "markdown" }
          - { label: "La nostra storia (sopra immagine)", name: "ourHistory1", widget: "markdown" }
          - { label: "La nostra storia (sotto immagine)", name: "ourHistory2", widget: "markdown" }

      - label: "Servizi"
        name: "services"
        file: "content/pages/services.md"
        fields:
          - {
              label: "Titolo",
              name: "title",
              widget: "string",
              default: "I nostri servizi",
            }
          - { label: "Cosa Facciamo", name: "body", widget: "markdown" }

      - label: "Partners"
        name: "partners"
        file: "content/pages/partners.md"
        fields:
          - {
              label: "Titolo",
              name: "title",
              widget: "string",
              default: "Azienda",
            }
          - {
              label: "Intestazione",
              name: "body",
              widget: "markdown",
            }

      - label: "Contatti"
        name: "contacts"
        file: "content/pages/contacts.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              default: "Contattaci",
            }
          - {
              label: "Indirizzo",
              name: "address",
              widget: "string",
              default: "Via Dante, 20",
            }

  - name: "partners-data"
    label: "Partners"
    folder: "content/partners-data"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image"}
  
  - name: "employees"
    label: "Personale"
    folder: "content/employees"
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Titolo di lavoro", name: "job", widget: "string" }
      - { label: "Foto", name: "picture", widget: "image"}
