backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "partners"
    label: "Partners"
    folder: "content/partners"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Logo", name: "logo", widget: "string" }